server:
  port: 1367

spring:
  application:
    name: api-gateway
  profiles:
    active:
      default

eureka:
  instance:
    prefer-ip-address: true
  client:
    register-with-eureka: true
    fetch-registry: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
zuul:
  prefix:  /api
  sensitiveHeaders:
#  routes:
#    # 수동 경로 매핑  http://localhost:5555/srve2/v1/~~
#    service1: /srve1/**
#    service2: /srve2/**

ribbon:
  ReadTimeout: 60000
  connection-timeout: 3000

management:
  endpoint:
    routes:
      enabled: true
    filters:
      enabled: true
  endpoints:
    web:
      exposure:
        include: routes, filters
