server:
  port: 8021

spring:
  application:
    name: service2 #스프링 컨피그의 디렉토리명 과 일치해야 함
  profiles:
    active:
      default

eureka:
  instance:
    prefer-ip-address: true
  client:
    register-with-eureka: true # 유레카 서비스에 (자신을) 등록 여부
    fetch-registry: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

management:
  endpoints:
    web:
      exposure:
        include: "*"