server:
  port: 9090

spring:
  kafka:
    bootstrap-severs:
      - localhost:9092
    consumer:
      enable-auto-commit: true
      auto-offset-reset: latest
#      group-id: waltergroup
#      auto-commit-interval: 1000ms #10초마다 커밋. 기본값 500ms(5초)
  data:
    mongodb:
      host: localhost
      port: 27017
      authentication-database: admin
      database: app_db
      username: root
      password: root
    redis:
      lettuce:
        pool:
          min-idle: 0
          max-idle: 8
          max-active: 8
      port: 6379
      host: localhost