server:
  port: 9090

spring:
  data:
    mongodb:
      host: localhost
      port: 27017
      authentication-database: admin
      database: app_db
      username: root
      password: root
    redis:
      lettuce:
        pool:
          min-idle: 0
          max-idle: 8
          max-active: 8
      port: 6379
      host: localhost